#!/usr/bin/env scheme
;;; run.scm
;;;
;;; Main entry point for running the Integral Semiotic Realism Pattern Archetype
;;; This script loads the modules and provides an interactive REPL

;; Load the pattern archetype implementation
(load "pattern-archetype.scm")
(load "test-pattern.scm")
(load "demo.scm")

;; ============================================================================
;; Main Menu
;; ============================================================================

(define (display-menu)
  (display "")
  (newline)
  (display "╔═══════════════════════════════════════════════════════════════╗")
  (newline)
  (display "║  INTEGRAL SEMIOTIC REALISM - PATTERN ARCHETYPE              ║")
  (newline)
  (display "╚═══════════════════════════════════════════════════════════════╝")
  (newline)
  (newline)
  (display "Choose an option:")
  (newline)
  (display "  1. Run all tests")
  (newline)
  (display "  2. Run all demonstrations")
  (newline)
  (display "  3. Display example archetype")
  (newline)
  (display "  4. Demo: Consciousness")
  (newline)
  (display "  5. Demo: Language")
  (newline)
  (display "  6. Demo: Science")
  (newline)
  (display "  7. Demo: Perspectives")
  (newline)
  (display "  8. Demo: NonDual Origin")
  (newline)
  (display "  9. Demo: Perception")
  (newline)
  (display " 10. Demo: Complex Systems")
  (newline)
  (display "  0. Exit")
  (newline)
  (newline)
  (display "Enter choice: "))

(define (handle-choice choice)
  (cond
    ((equal? choice "1") (run-all-tests))
    ((equal? choice "2") (run-all-demos))
    ((equal? choice "3") (display-archetype example-archetype))
    ((equal? choice "4") (demo-consciousness))
    ((equal? choice "5") (demo-language))
    ((equal? choice "6") (demo-science))
    ((equal? choice "7") (demo-perspectives))
    ((equal? choice "8") (demo-nondual))
    ((equal? choice "9") (demo-perception))
    ((equal? choice "10") (demo-complex-systems))
    ((equal? choice "0") (display "Goodbye!") (newline) #f)
    (else 
      (display "Invalid choice. Please try again.")
      (newline)
      #t)))

;; Interactive loop (commented out for non-interactive use)
;; (define (main-loop)
;;   (display-menu)
;;   (let ((choice (read-line)))
;;     (if (handle-choice choice)
;;         (main-loop))))

;; For scripted execution, just show the example
(define (main)
  (display "")
  (newline)
  (display "╔═══════════════════════════════════════════════════════════════╗")
  (newline)
  (display "║  INTEGRAL SEMIOTIC REALISM - PATTERN ARCHETYPE              ║")
  (newline)
  (display "║  Pure Scheme Implementation                                  ║")
  (newline)
  (display "╚═══════════════════════════════════════════════════════════════╝")
  (newline)
  (newline)
  (display "Loading modules...")
  (newline)
  (display "  ✓ pattern-archetype.scm")
  (newline)
  (display "  ✓ test-pattern.scm")
  (newline)
  (display "  ✓ demo.scm")
  (newline)
  (newline)
  (display "Example Archetype Instance:")
  (newline)
  (newline)
  (display-archetype example-archetype)
  (newline)
  (newline)
  (display "To run tests: (run-all-tests)")
  (newline)
  (display "To run demos: (run-all-demos)")
  (newline)
  (display "To run specific demo: (demo-consciousness), (demo-language), etc.")
  (newline)
  (newline))

;; Run main when script is executed
(main)
